### ISSUE TITLE
Bad mixing of double and single precision floating point

### ISSUE THREAD

**Issue by lycium** [ms0g/rt86#2]
E.g. here:

https://github.com/ms0g/rt86/blob/5232b894c613d6ac2de96abb24941f245c810368/SRC/SPHERE.CPP#L18

sqrt is the double precision function, sqrtf is the single precision version. This extends to all the trig functions, and numbers like 1.3 are double, 1.3f is the float.

If you're just going to rip the Ray Tracing in One Weekend code without credit and change the types, you should at least know what you're doing and properly audit the changes! :)

**Comment by ms0g** [comment]
There is no sqrtf in 16 bit era and I didn't want use double everywhere for performance considerations. 
<img width="289" alt="Screenshot 2024-10-30 at 02 05 44" src="https://github.com/user-attachments/assets/4c214e26-184b-42f9-9f99-6d1979e466fc">
